class RandomNamesGenerator {
    getRandom(): string {
        return RandomNames[Math.floor(Math.random()*RandomNames.length)]
    }
}

export default RandomNamesGenerator;

const RandomNames: string[] = [
    'Cesiola',
    'Tau Salcraft',
    'Jajcentesis',
    'Kylelect XIII',
    'Elementlogs',
    'Uranaut',
    'Gadobie',
    'Soliuous',
    'Urectonomics',
    'Thorality',
    'Asgpunk LI',
    'Tau Arrty',
    'Plulytic',
    'Argish LII',
    'Neodyand',
    'Asgsphere',
    'TOI-169 b',
    'Krymaths',
    'Vanaditude',
    'Sesholic',
    'Kronoorama',
    'Galest',
    'Cyteresplain',
    'Ardmax',
    'Actimancer LXXXII',
    'Lanthatropy',
    'Cobaltron',
    'HD 13167 b',
    'Arkangle',
    'Neochezia',
    'Solridden',
    'Kakes',
    'Venford',
    'Badive',
    'Boroproof',
    'Kryptoiatrics',
    'Radiuite',
    'Flathermy',
    'Asglith XVIII',
    'Titanigamous',
    'Lambda Skrbie',
    'Arseage',
    'Neoest',
    'Tellurphage',
    'Vorola',
    'Gallimancer',
    'Corandrous',
    'Potared',
    'Brotide',
    'Aaoic',
    'Flaonym',
    'Svacracy',
    'Tertopic',
    'Protaistical',
    'Platrope',
    'GJ 667 C e',
    'Uranogeddon',
    'Antiive',
    'Vanienne',
    'Hanphilia',
    'Astatinfu XXIX',
    'Nepangular',
    'Nowslang L',
    'Torlock',
    'Jupanth',
    'Hapanth',
    'Cyterecephalic',
    'Dregeddon',
    'Earnt',
    'Corylidene',
    'Vanadiylene',
    'Nickeies',
    'Saqose',
    'Earphilia',
    'Poloclase',
    'Berderm',
    'HD 143105 b',
    'Neodychan',
    'Ruthenipoly',
    'Burometry',
    'Jotgramme LI',
    'Cesirrhexis',
    'Magsson',
    'Cybtopic',
    'Kepler-1332 b',
    'Iridiatric',
    'Mavass',
    'Kitarch CXLI',
    'Lambda Rhoditopia',
    'Gadoacious',
    'K2-264 b',
    'Wolfrafree',
    'Jajcephalic',
    'Carcoele',
    'Pranymy',
    'Joline',
    'Krienchyma',
    'Salgraphical',
    'Hydrocrat',
    'Earcrasy',
    'Xaxlike',
    'Sodiunt',
    'Hydroed',
    'Cronudromous',
    'Upsilon Niobirrhagia',
    'Sanstan CXLVIII',
    'Pallayl',
    'Uratropism LXXV',
    'Saqex',
    'Poseidomer',
    'Pogsauce',
    'Uraa',
    'Europitome',
    'Zeta Zircorrhoea',
    'Galistical',
    'Voganthropy',
    'Corine',
    'Kepler-850 b',
    'Beriatrician CXXXVI',
    'Rho Lazhead',
    'Nitrostyly',
    'Nitrogate',
    'Jola',
    'Vanphyll',
    'Telluay',
    'Omega Lunaacal',
    'Ceridom',
    'Heliuphilia',
    'Pyrstatin',
    'Solamancer',
    'Fluoridynia',
    'Badcide',
    'Krychan',
    'Dreet',
    'Terranazi',
    'Sesacity',
    'Astatincephalic',
    'Froways',
    'Vornasty',
    'Gomane',
    'Radoarchy',
    'Molyphilic',
    'Nornheim',
    'Urectolingual',
    'Astatinlogue',
    'Pyrule',
    'Kitennial',
    'Arrdermatous',
    'Radopath',
    'Allstyly',
    'Aluminugenin CXLV',
    'Earmeal',
    'Lutetimaniac',
    'Badstan',
    'Selenoiatrics',
    'HATS-51 b',
    'Sigma Rhodilike',
    'Gibtherm',
    'Cobalsson',
    'Kepler-123 b',
    'Meric LXXI',
    'Torhead',
    'Damite',
    'Putonipexy',
    'beta Umi b',
    'Heliuiot',
    'Kepler-404 c',
    'Technezoan',
    'Krycocci',
    'Brofag',
    'Platinumaths',
    'WASP-69 b',
    'Carproof',
    'Heliucarp',
    'Actitastic',
    'Riaanthropy Omicron',
    'KIC 7917485 b',
    'HATS-26 b',
    'Lamassed',
    'Kepler-1370 b',
    'Kepler-644 b',
    'Germaambulist',
    'Lamphrenia',
    'Jajsaurus',
    'Zimalacia L',
    'Ardfree',
    'Berred',
    'K2-9 b',
    'Arret XCI',
    'OGLE-2011-BLG-0420L b',
    'Arrclase',
    'Falform LXXIX',
    'Aragrave',
    'Magwick',
    'BD+14 4559 b',
    'Arkclinal',
    'Coppeiatrics',
    'Thallpathic',
    'Solabury',
    'Elementist',
    'Kepler-1592 b',
    'Iota Berast',
    'Nowern',
    'Potaance',
    'Saturnosplain',
    'Skrgrave',
    'Nepyl',
    'Jikodont CXXIII',
    'Arago-7',
    'Hawnaut',
    'K2-33 b',
    'Cesithermy',
    'Sqoidine',
    'Barand',
    'WASP-10 b',
    'Earphyl CV',
    'Narmalacia',
    'Mangansaurus',
    'Chlorander',
    'Rupopsy',
    'Urectoae',
    'Sovkin',
    'Sqophone',
    'Titchoron',
    'Trimore',
    'Saqyl',
    'Iroine',
    'Beta Asgstatin',
    'Joviomata LXIX',
    'Satsies',
    'Heliucidal',
    'Zircometry',
    'Antiville',
    'Upsilon Chred',
    'Manganern',
    'Jollin',
    'Iodiylene',
    'Kronoparous',
    'Aakglot',
    'Argobury',
    'Iodia',
    'Epsilon Hapgraphical',
    'Pluadenia',
    'Nartopic CXLVI',
    'Samaristat',
    'Arkcocci',
    'Pyrbility',
    'Holmor',
    'Kepler-12 b',
    'Lutetiville',
    'YZ Cet b',
    'Magnesiuismus',
    'Germamane',
    'Parpounder',
    'Tantastomy',
    'Xproof',
    'Contron',
    'TOI-1130 b',
    'Cesipathy',
    'Lantharrhea',
    'Noronomy',
    'Badwide',
    'Oxykins',
    'Xaxgasm',
    'Jupmance',
    'Selenonazi',
    'Plagerous',
    'Bertown',
    'Rutheniphone',
    'Salnik XII',
    'Thallcoccus',
    'Urectogenesis',
    'Barmanship',
    'Traphyte',
    'WASP-157 b',
    'Jikhenge',
    'WASP-117 b',
    'Chlorane',
    'Krigramme LXXI',
    'Sivome',
    'Magamine',
    'Selenostomy III',
    'Poloemia',
    'Asgsome',
    'Siliot',
    'Galliend',
    'Earselves',
    'Urast',
    'Broopsy',
    'Conee',
    'Kepler-124 d',
    'HD 77338 b',
    'Berylliuical',
    'Polowork',
    'Mercuriometry',
    'Urectomaths',
    'Sanperson',
    'Falmeister',
    'HIP 57274 d',
    'Osmisome CV',
    'Jikylidene',
    'Neoia',
    'Rhodiïng',
    'Gaeaistic',
    'Danaire',
    'Areoola',
    'Sivagog',
    'Neothermal',
    'Nepagogy CVIII',
    'Kriienne',
    'Kepler-1125 b',
    'Gofurter',
    'Kepler-1678 b',
    'Easeen',
    'Kepler-154 b',
    'Hawsphere',
    'Gamma Cesimer',
    'Thorwich',
    'Rhenipath',
    'Iota Rhenigonal',
    'Golcephalic',
    'Carbokins',
    'Pluanthropy XXXIII',
    'Ytterbiuer',
    'Kepler-484 b',
    'Badkind',
    'Vilchoron',
    'Praseologue',
    'Dampath XI',
    'Titferous',
    'Nixrrhexis',
    'Hermetied',
    'Cybphagy',
    'Manganwick',
    'Jovidiadenia',
    'Chromist',
    'Conanthropy Delta',
    'Contopic',
    'Satage',
    'Xanry',
    'Svaeer',
    'Areoman',
    'Nepostomy',
    'Sanery',
    'Chi Saqand',
    'Veneriamine',
    'Lazlogy',
    'Nitroarian',
    'Soliman',
    'Dysprosgrave',
    'Terracrasy CVI',
    'HD 11964 c',
    'Thallassed',
    'Jotscope',
    'Eta Salarch',
    'Earmageddon',
    'Xarandrous',
    'Froadenia',
    'Saturnourgy',
    'Mavth',
    'Lunashire',
    'Sigma Hapopsia',
    'Europiite',
    'Gagphyll',
    'Prephone',
    'Urauret',
    'Falpunk',
    'Hadeagamous',
    'Franciæ',
    'Tertude',
    'Damthermy',
    'Niobispeak',
    'Beta Egolike',
    'Cronufurter',
    'Uraally',
    'Mavwork CVI',
    'Morambulist',
    'Cybwick',
    'Jovidiostomy',
    'Omega Niobionium XXX',
    'Magmeal LXXXIX',
    'Oxyholic Omega',
    'YBP401 b',
    'DRcha',
    'Torance',
    'Iridferous',
    'Bariall',
    'Francint',
    'Saturniette',
    'Lithiuagogy',
    'Vormen',
    'Jovilytic',
    'Uranology Rho',
    'Neodyphonic',
    'Hawtard',
    'Nixist',
    'Asbmantic',
    'Asgoholic CL',
    'Platude',
    'Vanoholic',
    'Kepler-30 c',
    'Jajmas',
    'Sigma Arritis',
    'Saqiasis',
    'Terbiumalacia',
    '18 Del b',
    'Zircothermal',
    'Zeta Merdar CII',
    'Aluminution',
    'Trarrhoea',
    'Kryptolept',
    'Parmer',
    'Holmmorphy',
    'Kepler-339 d',
    'Falon',
    'Aaes',
    'Erbiid',
    'Nepmere XXXVIII',
    'Areocaine',
    'Lithiuholic IV',
    'Sivmost',
    'Cadmigamy',
    'Geoander',
    'Rhodiylidene',
    'Hartide',
    'Solaville',
    'Kepler-1028 b',
    'Kriance',
    'Yttriphyll',
    'Terary',
    'Niobiparous',
    'Magnesiupathic',
    'Earperson',
    'Aaeous',
    'Vanbon',
    'Morsphere V',
    'Phi Hapopsia C',
    'Gibonomics',
    'Capagogue',
    'Lithiuelect',
    'Strcentesis',
    'Gaeaern',
    'Gamma Hawzoan',
    'Barriffic',
    'Cronuine',
    'Terion',
    'Heliutard XXXI',
    'Techneastic',
    'Stramine',
    'Ruthenishire',
    'Juplith',
    'Dansky',
    'Hawistically',
    'Paring CV',
    'Chlorica',
    'Pluto',
    'Thulithermic',
    'Tellueer',
    'Corgraphical IX',
    'Silcene',
    'Zenholic',
    'Theta Pyrmentum',
    'Astatingamous',
    'Chrpnea',
    'Cononomics XLIII',
    'Upsilon Tantanaut',
    'Jupist',
    'Galileaista',
    'Hermetilogy',
    'Urafaction',
    'Neptropy',
    'Jupotic',
    'HIP 79431 b',
    'Vanomata',
    'Arritis',
    'Kepler-1488 b',
    'Strontiuelect',
    'Drelog',
    'Burrrhea',
    'Parred',
    'Jovidiiasis',
    'Musor',
    'Indiadic',
    'Marphone',
    'Sodiugrave',
    'Nickeable',
    'Cormobile',
    'Gonym',
    'Norzygous',
    'Narform',
    'Jovidipnea',
    'Coppeish',
    'Hermetiphagia',
    'Urakun',
    'Erothermy',
    'Merproof',
    'Jaggasm',
    'Dreadenia',
    'Europired',
    'Nanpoly LII',
    'Kakarium',
    'Wolfratown',
    'Lazbound',
    'Gamma Aratort',
    'Yttriistic',
    'Hermetipounder',
    'Argoet',
    'Praical',
    'Blaclase',
    'K2-4 b',
    'Kritomy',
    'Gadoite',
    'Radiuylene',
    'HD 45364 b',
    'Cytereiot',
    'Holmonomy',
    'Saturnonaut',
    'Chronyca-2',
    'Blaive',
    'Platinuola',
    'Pogess',
    'Veneriose',
    'Ardistical',
    'Ardist',
    'Pyrpolises',
    'Germaville',
    'Calciugerous',
    'Fluoriomas',
    'Terratome',
    'Chromsome',
    'Dreric',
    'Lunaenchyma',
    'Holmxeny',
    'Sesgenesis',
    'Saknymy',
    'Nixlings',
    'Marmere',
    'Poglepsy LXXIII',
    'Kepler-1306 b',
    'Pogetic',
    'Telluoi',
    'Sqolith',
    'Venerigate',
    'Parer',
    'LHS 1140 c',
    'Sodiuonymy',
    'Stulet',
    'Terratome',
    'Kriistic',
    'Hapoic acid',
    'Hapile',
    'Yttriismus',
    'Cadmiar',
    'Cronuform',
    'Pallagamy',
    'Buracious CXIX',
    'Cona',
    'Earmas',
    'Astatinmane',
    'Tau Heliuite',
    'Badlept',
    'Molymerous',
    'Araance',
    'Soliridden',
    'Eascidal',
    'Bismukins',
    'Arryne',
    'Francigenic',
    'Xardar',
    'Dysprosed',
    'Galileaphasia',
    'Alfacity',
    'Plualgia Rho',
    'Hermetiial',
    'Vilwich',
    'Morstyle',
    'Tellurtype',
    'Kepler-412 b',
    'Mormer',
    'Egofugal',
    'Magnesiuandrous',
    'Zitide',
    'Uranoarch CIV',
    'Pallation',
    'Omega Gocorn',
    'Galileabiotic',
    'Seleniagogue',
    'Sancardia',
    'Damnasty',
    'Cyterecolous',
    'Solpnea',
    'HD 87646 A b',
    'Marform',
    'Musphagy',
    'Sigma Hadeasky',
    'Gibplast',
    'Skrmorphous',
    'Dergerous',
    'Riamas',
    'Oxylin',
    'Burmentum',
    'Nitrorrhœa',
    'Gibville LXIII',
    'Marclase',
    'Epsilon Kryptorrhœa',
    'Presium',
    'HD 125595 b',
    'Potaphonic',
    'Heliosaurus',
    'Nitrograve',
    'Titillion',
    'Egoadenia',
    'Kepler-869 b',
    'Titino I',
    'Phosphopolises',
    'Saturnoiatry',
    'Niobiphyll',
    'Galmance',
    'Hawennial',
    'Erbiet XLVIII',
    'Nanitis',
    'Praseophagia',
    'Hanmorphy',
    'Egoitis',
    'Hermetipterous',
    'HIP 109384 b',
    'Burxeny',
    'Allsphere',
    'Neoend',
    'Uranococci',
    'Cybrrhea',
    'Egoplasia',
    'Toryl',
    'Nanally',
    'Giblogues',
    'Dermane XCIX',
    'Terraiasis',
    'Kepler-194 b',
    'Aluminution',
    'Arsepoly',
    'Gadomeister',
    'Sivpounder',
    'Neodygraph LXXXV',
    'Vilkin',
    'K2-223 b',
    'Dagty',
    'Poseidokins',
    'Noruous',
    'Protaey XCIX',
    'Krigenin',
    'Aakcocci',
    'Radiucline',
    'Jovidially CXXXVIII',
    'Barior',
    'Kepler-825 b',
    'Sqoleptic CXXVIII',
    'Frolalia CV',
    'Badite',
    'Kepler-880 b',
    'Narate',
    'HATS-21 b',
    'Uralandia',
    'Neptuniadic',
    'Vencha',
    'Burphon XII',
    'Jajometry',
    'Goed',
    'Jajself',
    'Hadeaoid CII',
    'Strall',
    'Poseidoish LXV',
    'Sesoid',
    'HD 106574 b',
    'Bismuchezia',
    'Blaphyl',
    'Bermas',
    'Urectostasis',
    'Vogphilia',
    'Technecratic',
    'Phosphoancy',
    'OGLE-2015-BLG-0051L b',
    'Uragrapher',
    'Mercuriest',
    'Hafnisson',
    'Rheniino',
    'Egogerous',
    'Hangen',
    'Leaine',
    'WASP-4 b',
    'Zeta Neoonomics',
    'Uranotome',
    'HAT-P-23 b',
    'Zenonomics',
    'Saturniist XXVI',
    'Hydrocoele',
    'Eroable',
    'Harphasia',
    'Precene',
    'Sakperson',
    'Xi DRmost',
    'Ardsion',
    'Eta Bariyl CXXXVIII',
    'Praseoadenia',
    'Galileaexia',
    'Kepler-363 c',
    'Veneriwork',
    'HD 120084 b',
    'Asgel',
    'Plaotic',
    'HAT-P-32 b',
    'Cesiman',
    'Torive',
    'Kryemia',
    'Selenimicin',
    'Chromule',
    'Vanle',
    'Tantaian',
    'Marst',
    'Erbiamundo LXXXVII',
    'Thoriasis LXXVII',
    'Nifium',
    'KELT-1 b',
    'HD 34445 c',
    'Indirrhexis',
    'Badmer',
    'Merose',
    'Soliandry',
    'S Ori 68',
    'Aakitis',
    'Kepler-1039 b',
    'Mavtropy',
    'Fluorisoft',
    'Osmidom',
    'Germaergy',
    'Burpetal XLIV',
    'Arrslang',
    'Eta Sespetal',
    'Elementette XCV',
    'Radiulingual',
    'Rhodiholism',
    'Osmiandry',
    'Gallicarp',
    'Xarman III',
    'Sodiumantic',
    'Kepler-1086 b',
    'OGLE-2012-BLG-0563L b',
    'Egocrat',
    'Hawville',
    'Thallvalent CXXXII',
    'HD 40956 b',
    'Solicoccus',
    'Radotide',
    'Lunaangle',
    'Lanthaey',
    'Asgron',
    'Musomics',
    'Poseidoium Gamma',
    'Capcolous',
    'Hariatry',
    'Conex',
    'KMT-2018-BLG-1990L b',
    'Egofaction',
    'Praphonic',
    'Sivarium',
    'Betone',
    'Conphyll',
    'Hafniies',
    'Asgcha',
    'Urectoass',
    'Nickeron',
    'Kepler-1465 b',
    'Gaeaery XXXIX',
    'Berylliunema',
    'Svaotic',
    'Meride',
    'Hawose',
    'Pargasm',
    'Sqoola',
    'Vanacious',
    'Dagleptic',
    'Nitropathy',
    'Cadmiule',
    'Lanthaar',
    'Promeacharya',
    'Derplast',
    'Neoiatrics',
    'Strontiuium',
    'Gadoodontia XCIII',
    'Asbish CXXII',
    'Pladerm',
    'Egont',
    'Silmeter',
    'Kepler-233 b',
    'Satennial',
    'Narmania',
    'Kronoopsia',
    'Elementopia XXIV',
    'Titaniphile LXIV',
    'Rubidiandrous',
    'Falopsy',
    'Actiwad',
    'Kepler-915 b',
    'Berylliuage XCIV',
    'Ardtome',
    'Chlorers',
    'Carend',
    'Goometry',
    'Polooid',
    'Zeta Nowkin',
    'HD 240210 b',
    'Poseidoast',
    'Asgpetal',
    'Hydrochory XLVIII',
    'Hafnigerous',
    'Xenoese XXXVI',
    'Borobiotic',
    'Nepcratic',
    'Teragog',
    'Gibdermatous',
    'HD 158996 b',
    'Nixangular CXXXII',
    'Vaner',
    'Worite',
    'Nifpunk',
    'WASP-127 b',
    'Trarrhaphy',
    'GJ 480 b',
    'Titaniome',
    'Fladromous',
    'HAT-P-24 b',
    'Jovipoly',
    'Germaaire',
    'Aramania',
    'Arseiatrician',
    'Asggeddon',
    'Solzoan',
    'Easene',
    'Borolandia',
    'Kylferous',
    'Elementyl',
    'Niobigasm',
    'Xenoine',
    'Neodyagogue',
    'Cortropy',
    'Argies CVII',
    'Manganphasia',
    'Eartrope',
    'Golric',
    'Gagary',
    'Theta Sodiuometer',
    'Rubidiurgy',
    'Vilistic',
    'Geocha',
    'Jotion',
    'Arkmorphic',
    'Alpha Technemancer',
    'Nitrophyll',
    'Kepler-1055 b',
    'Badfaction',
    'Selenoshire',
    'Cyterephile',
    'Techneers',
    'Dreborn',
    'Aakgerous XCIX',
    'Xenobiont',
    'Barblast LV',
    'Cartown',
    'Calciuadenia',
    'Thallridden LXXX',
    'Sulfurgy',
    'Samarialgia',
    'Gocene',
    'Plua',
    'Terraene',
    'Asglogue',
    'Telluand',
    'Kryphonic',
    'Pluscope',
    'Veneriino',
    'Chlorar',
    'Zircozoan LVI',
    'Aagenesis Phi',
    'Aakbility',
    'Gooholic',
    'Korsies',
    'Lutetimania',
    'Chromennial',
    'Betsies',
    'Cesitherm',
    'Iota Sqoangle CXXV',
    'HD 83443 b',
    'Radiuridden',
    'Manganwork',
    'Bladom',
    'Protalog CXXI',
    'Galliic',
    'Radobiont',
    'Urscephalic',
    'Nepese',
    'Arktastic',
    'Omega Flaennial',
    'Falers',
    'Betæ CVI',
    'Nixonomy',
    'Conine',
    'Earstomy',
    'Heliotastic',
    'Saqzoan',
    'Sanfree',
    'Burle',
    'Morman',
    'XO-6 b',
    'Torpants',
    'Kepler-852 b',
    'Samariid',
    'Tinomics',
    'Terlalia',
    'Jajoon I',
    'Thulidom',
    'Neptunity',
    'Kepler-178 c',
    'Aakmax',
    'Kormachy Xi',
    'Sivsion',
    'Asglytic',
    'MOA-2012-BLG-505L b',
    'Sulfistic',
    'Arseide',
    'Xcoccus',
    'Nitrolike',
    'Falkind',
    'Erbibiotic',
    'Chromometer',
    'Jolage',
    'Lunanymy',
    'Asgmancer',
    'Marlingual',
    'Dergaze',
    'Sivoid XXI',
    'Neooth',
    'Satsoft',
    'Satcraft',
    'Krygrave',
    'Musrrhœa',
    'Kepler-1654 b',
    'Satagogy',
    'Wormancer',
    'Caraire',
    'Galligaze',
    'Jovidimorphy',
    'Kryptoiana',
    'Danmaniac',
    'Jotpexy',
    'Zenfix',
    'Lithiuthermic',
    'Scandiuastic LXVIII',
    'K2-3 d',
    'Telluracity',
    'Nixrices',
    'Nixyne',
    'Merby',
    'Thuliee',
    'Geoeous',
    'Silander',
    'Jajian',
    'Sovmere',
    'Conmane',
    'Lampnea',
    'Holmstomy',
    'Putoniderma',
    'Chlormerous',
    'Vogst',
    'Kepler-889 b',
    'Uraillion',
    'Xanex',
    'Luteticoccus',
    'Neprrhagia',
    'Kricocci',
    'Coppeomata',
    'Chi DRacharya',
    'Norome',
    'Kepler-1498 b',
    'Eta Musese',
    'Protaor',
    'Narid',
    'Pallaally',
    'Saqphagy',
    'Geoand',
    'Sulftomy',
    'Kepler-85 d',
    'Antifugal',
    'Hawgenin',
    'Gallimance',
    'Boroderma',
    'Berylliuey',
    'Selenieer',
    'Aagen',
    'Norwick',
    'Asgee',
    'Aasoft'
]
